from . import fleet_vehicle
from . import fleet_vehicle_cost
from . import res_partner
from . import hr_employee
from . import pnt_circulation_permit_class
from . import res_company
from . import res_config_settings
from . import pnt_transport_card
from . import pnt_fleet_vehicle_category
from . import product_template
from . import pnt_logos
from . import pnt_product_marpol_waste_category
from . import pnt_product_tmpl_waste_table
from . import pnt_product_tmpl_waste_ler
from . import pnt_purchase_bill_union
from . import pnt_waste_nima_code
from . import pnt_waste_authorization_code
from . import pnt_partner_waste_table
from . import pnt_agreement_agreement
from . import pnt_general_conditions
from . import pnt_control_sheet
from . import pnt_single_document
from . import project_task
from . import purchase_order
from . import resource_calendar
from . import stock_picking
from . import sale_order
from . import account_fiscal_position
from . import pnt_scales
from . import pnt_scales_record
from . import account_bank_statement
from . import account_move
from . import account_payment_mode
from . import pnt_container_movement
from . import account_tax
from . import res_users
from . import pnt_agreement_lot
from . import pnt_logistic_route
from . import pnt_waste_nima_operator_type
from . import crm_lead
from . import product_category
from . import product_product
from . import pnt_agreement_registration
from . import pnt_base_address_city
from . import pnt_global_time_off
from . import pnt_waste_transfer_document
from . import pnt_project_task_reason
from . import pnt_boat_type
from . import pnt_product_marpol_waste_annex
from . import crm_stage
from . import calendar
from . import uom
from . import account_asset
from . import account_journal
from . import hr_employee_base
from . import pnt_carrier_zone
from . import pnt_carrier_rate
