{
    "name": "Website Customizations PNT",
    "summary": "New functionalities to solve customer's needs in website",
    "version": "14.0.1.0.0",
    "category": "Custom",
    "website": "https://www.puntsistemes.es",
    "author": "Punt Sistemes",
    "maintainers": [
        "sbenlloch",
    ],
    "license": "LGPL-3",
    "application": False,
    "installable": True,
    "depends": [
        "custom_pnt",
        "report_pnt",
        "web",
        "portal",
        "sale",
        "project",
        "hr_timesheet",
        "helpdesk",
        "purchase",
        "account",
    ],
    "data": [
        "views/portal_my_home_templates.xml",
        "views/portal_pnt_agreement_agreement_templates.xml",
        "views/portal_pnt_single_document_templates.xml",
        "views/portal_pnt_waste_transfer_document_templates.xml",
        "views/portal_pnt_agreement_registration_templates.xml",
        "views/portal_pnt_single_document_line_templates.xml",
        "views/account_portal_templates.xml",
    ],
}
