from . import pnt_app_du
from . import pnt_app_user
from . import pnt_app_application
from . import pnt_app_session
from . import product_template
from . import pnt_single_document
from . import pnt_app_tag_log
from . import pnt_app_tag
from . import product_product
from . import res_partner