{
    "name": "Programaciones Odoo app Adalmo",
    "summary": "Programaciones Odoo app Adalmo",
    "version": "14.0.1.0.0",
    "category": "Hidden",
    "website": "https://www.puntsistemes.es",
    "author": "Punt Sistemes",
    "maintainers": [
        "Tolo Torres",
    ],
    "license": "LGPL-3",
    "application": False,
    "installable": True,
    "depends": [
        "custom_pnt",
        "base",
    ],
    "data": [
        "data/ir_cron.xml",
        "security/res_groups.xml",
        "security/ir.model.access.csv",
        "security/security.xml",
        "reports/pnt_print_tag.xml",
        "wizards/pnt_app_tag_manual_views.xml",
        "wizards/pnt_app_du_change_views.xml",
        "views/pnt_app_du_views.xml",
        "views/pnt_app_application_views.xml",
        "views/pnt_app_tag_log_views.xml",
        "views/pnt_app_tag_views.xml",
        "views/pnt_app_user_views.xml",
        "views/pnt_app_session_views.xml",
        "views/product_template_views.xml",
        "views/res_partner_views.xml",
        "views/pnt_single_document_views.xml",
    ],
}
